# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v -s -m shah --html=config/report.html
    - name: Upload content
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: config/

  release:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    needs: build
      
    steps: 
      - name: Generate random tag
        id: random-tag
        run: echo "TAG=$(uuidgen)" >> $GITHUB_ENV
        
      - uses: actions/download-artifact@v3
        with:
          name: test-report
          path: ./reports/
      - run: zip -r reports.zip reports/
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          artifacts: "reports.zip"

      - name: Send email with artifacts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          subject: "test report"
          to: shahbazsyed496@gmail.com
          username: "shahshahbaz64@gmail.com"
          password: "app password"
          from: shahshahbaz64@gmail.com
          body: |
            Hi,
            its a test report email.
            Regards,
            abc
          attachments: |
            reports.zip
